### ISSUE TITLE
Lower minimum Android SDK level to 23

### ISSUE THREAD

**Issue by BjoernPetersen** [CoraLibre/CoraLibre-android-sdk#25]
The minimum Android SDK level is 26 right now. We should lower that to at least 23, which would be the same as the official API.

**Comment by theScrabi** [comment]
I've set it to 26 because [this part](https://github.com/CoraLibre/CoraLibre-android-sdk/blob/1c8340fea9c880fe7456886d5433fbedde86e003/coralibre-sdk/sdk/src/main/java/org/coralibre/android/sdk/internal/bluetooth/BleServer.java#L89) is only available from this sdk version on. If we can replace it by [this](https://github.com/CoraLibre/CoraLibre-android-sdk/blob/1c8340fea9c880fe7456886d5433fbedde86e003/coralibre-sdk/sdk/src/main/java/org/coralibre/android/sdk/internal/bluetooth/BleServer.java#L100) line we can go back to 23. However I am not sure if the setting I used here matches the required specification of the protocol.
